# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(210, 470, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(50, 470, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(420, 470, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(590, 470, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        self.txt_plaintext = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_plaintext.setGeometry(QtCore.QRect(90, 60, 251, 161))
        self.txt_plaintext.setObjectName("txt_plaintext")
        self.txt_infomation = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_infomation.setGeometry(QtCore.QRect(510, 60, 251, 161))
        self.txt_infomation.setObjectName("txt_infomation")
        self.txt_ciphertext = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_ciphertext.setGeometry(QtCore.QRect(90, 270, 251, 161))
        self.txt_ciphertext.setObjectName("txt_ciphertext")
        self.txt_signature = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_signature.setGeometry(QtCore.QRect(510, 270, 251, 161))
        self.txt_signature.setObjectName("txt_signature")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(386, 90, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(396, 280, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 280, 61, 16))
        self.label_4.setObjectName("label_4")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(170, 20, 151, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.label.setText(_translate("MainWindow", "Plaintext:"))
        self.label_2.setText(_translate("MainWindow", "Infomation:"))
        self.label_3.setText(_translate("MainWindow", "Signature: "))
        self.label_4.setText(_translate("MainWindow", "Cipher text:"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Keys"))
